bccmd: bccmd.c csr.c  csr_3wire.c  csr_bcsp.c  csr_h4.c  csr_hci.c  csr_usb.c ubcsp.c
	gcc -lbluetooth -lusb csr.c  csr.h  csr_3wire.c  csr_bcsp.c  csr_h4.c  csr_hci.c  csr_usb.c ubcsp.c bccmd.c -o bccmd
