.TH FANG 1 "Apr 20 2003" Fang "Linux System Administration"
.SH NAME
fang \- Hunt bluetooth devices
.SH SYNOPSIS
.B fang [-h]
.br
.B fang [-i <hciX>] [command [command parameters]]

.SH DESCRIPTION
.LP
.B
fang
is used to hunt bluetooth devices down
.SH AUTHORS
Written by Ollie Whitehouse <ollie@atstake.com>
.PP
man page by Ollie Whitehouse <ollie@atstake.com>
